<?php

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;

class RolesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $roles = [
        // 			'Main Administrator',
        // 			'HR',
        // 			'Management',
        // 			'DGM',
        // 			'GM',
        // 			'HOD',
        // 			'Dy.HOD',
        // 			'CMD',
        // 			'MD',
        // 			'Center Manager',
        // 			'Computer Clerk',
        // 			'Counsellor',
        // 			'Data Entry Operator',
        // 			'DEO',
        // 			'District Project Manager',
        // 			'Supervisor',
        //             'Machine Operator',
        //             'Guard'
        // 		 ];

        // foreach ($roles as $key => $value) {
		//  	Role::create(['name' => $value]);
		// }
		DB::statement("INSERT INTO `roles` (`name`, `guard_name`, `created_at`, `updated_at`) VALUES
		('A.M.', 'web', NULL, NULL),
		('Main Administrator', 'web', NULL, NULL),
		('ABM', 'web', NULL, NULL),
		('Account Expert', 'web', NULL, NULL),
		('Accountant', 'web', NULL, NULL),
		('ADM', 'web', NULL, NULL),
		('Adminstration Finance', 'web', NULL, NULL),
		('AGM', 'web', NULL, NULL),
		('APO', 'web', NULL, NULL),
		('APO Cum Computer Programmer', 'web', NULL, NULL),
		('Application Admin', 'web', NULL, NULL),
		('Application Developer-1', 'web', NULL, NULL),
		('Application Devoloper-I', 'web', NULL, NULL),
		('Application Devoloper-II', 'web', NULL, NULL),
		('Application Software Administrator', 'web', NULL, NULL),
		('Area Manager', 'web', NULL, NULL),
		('Assistant', 'web', NULL, NULL),
		('Assistant Cook', 'web', NULL, NULL),
		('Assistant DEO', 'web', NULL, NULL),
		('Assistant Make up Trainer', 'web', NULL, NULL),
		('Assistant Manager', 'web', NULL, NULL),
		('Assistant skin trainer', 'web', NULL, NULL),
		('Assitant Executive (IT)', 'web', NULL, NULL),
		('Assitant Executive (production)', 'web', NULL, NULL),
		('ASSOCIATE ENGINEER', 'web', NULL, NULL),
		('Associate Enginer', 'web', NULL, NULL),
		('ASSOCIATE SUPERVISOR', 'web', NULL, NULL),
		('Asst. D.E.O', 'web', NULL, '2019-04-15 07:31:02'),
		('Asst. Manager', 'web', NULL, NULL),
		('Asst. Professor', 'web', NULL, NULL),
		('Asst. System Admin', 'web', NULL, NULL),
		('BC', 'web', NULL, NULL),
		('Beatucian', 'web', NULL, NULL),
		('Beautician', 'web', NULL, NULL),
		('Beaution', 'web', NULL, NULL),
		('Beauty Trainer', 'web', NULL, NULL),
		('Beutician', 'web', NULL, NULL),
		('Block Coordinator', 'web', NULL, NULL),
		('Block Project Assistant', 'web', NULL, NULL),
		('Book Binder', 'web', NULL, NULL),
		('BPA', 'web', NULL, NULL),
		('Business Analyst', 'web', NULL, NULL),
		('Call Centre Executive', 'web', NULL, NULL),
		('Car Jeep Driver', 'web', NULL, NULL),
		('Carpainter', 'web', NULL, NULL),
		('Cattel Scarer', 'web', NULL, NULL),
		('CCDC', 'web', NULL, NULL),
		('CCE', 'web', NULL, NULL),
		('Center Manager', 'web', NULL, NULL),
		('CEO', 'web', NULL, NULL),
		('Chowkidar', 'web', NULL, NULL),
		('City Mission Manager', 'web', NULL, NULL),
		('Civil Engineer', 'web', NULL, NULL),
		('Cleark', 'web', NULL, NULL),
		('CLTC-Civil Engineer', 'web', NULL, NULL),
		('CMM', 'web', NULL, NULL),
		('CMM-Finance', 'web', NULL, NULL),
		('CMM-MIS', 'web', NULL, NULL),
		('CMM-SMID', 'web', NULL, NULL),
		('CO', 'web', NULL, NULL),
		('Collection Officer', 'web', NULL, NULL),
		('Community Organiser', 'web', NULL, NULL),
		('Community Organiser\'s', 'web', NULL, NULL),
		('Computer Clerk', 'web', NULL, NULL),
		('Computer Op.', 'web', NULL, NULL),
		('Computer Operator', 'web', NULL, NULL),
		('Computer Teacher', 'web', NULL, NULL),
		('Consultant', 'web', NULL, NULL),
		('Consultant (Civil)', 'web', NULL, NULL),
		('Consultant (M&E and Decentralized Planning)', 'web', NULL, NULL),
		('Consultant (Nutrition & Child Development)', 'web', NULL, NULL),
		('Consultant (Procurement)', 'web', NULL, NULL),
		('Consultant (Social Development)', 'web', NULL, NULL),
		('Consultant- CB', 'web', NULL, NULL),
		('Consultant- DP', 'web', NULL, NULL),
		('Consultant-IEC', 'web', NULL, NULL),
		('Cook', 'web', NULL, NULL),
		('Coordinator Assistant', 'web', NULL, NULL),
		('Counsellor', 'web', NULL, NULL),
		('CP', 'web', NULL, NULL),
		('CRE', 'web', NULL, NULL),
		('CRM-Backend Executive', 'web', NULL, NULL),
		('D.E.O', 'web', NULL, NULL),
		('Dairy Technician', 'web', NULL, NULL),
		('DAM', 'web', NULL, NULL),
		('Data Entery Operator', 'web', NULL, NULL),
		('Data Entry Operator', 'web', NULL, NULL),
		('Database Administrative', 'web', NULL, NULL),
		('DELIVERY BOY', 'web', NULL, NULL),
		('DEO', 'web', NULL, NULL),
		('Deployment Coordinator', 'web', NULL, NULL),
		('Developer', 'web', NULL, NULL),
		('DGM', 'web', NULL, NULL),
		('Dietcian', 'web', NULL, NULL),
		('Dietician', 'web', NULL, NULL),
		('Diploma Eng.', 'web', NULL, NULL),
		('District Account Manager', 'web', NULL, NULL),
		( 'District Coordinator', 'web', NULL, NULL),
		( 'District Project Assistant', 'web', NULL, NULL),
		( 'District Project Manager', 'web', NULL, NULL),
		( 'Distt Project Assistant', 'web', NULL, NULL),
		( 'DO', 'web', NULL, NULL),
		( 'DO FIRE', 'web', NULL, NULL),
		( 'Dot Net Developer', 'web', NULL, NULL),
		( 'DPA', 'web', NULL, NULL),
		( 'DPM', 'web', NULL, NULL),
		( 'Driver', 'web', NULL, NULL),
		( 'Driver (Fire)', 'web', NULL, NULL),
		( 'Driver Operator', 'web', NULL, NULL),
		( 'Driver Operator (Fire)', 'web', NULL, NULL),
		( 'Driver Opt', 'web', NULL, NULL),
		( 'Drivr', 'web', NULL, NULL),
		( 'Electrical Consultant', 'web', NULL, NULL),
		( 'Electrician', 'web', NULL, NULL),
		( 'Engineer', 'web', NULL, NULL),
		( 'Environmemt & Water Quality Consultant', 'web', NULL, NULL),
		( 'EW &QC', 'web', NULL, NULL),
		( 'EXCUTIVE', 'web', NULL, NULL),
		( 'Executive', 'web', NULL, NULL),
		( 'Executive Assistant', 'web', NULL, NULL),
		( 'Executive Capacity Development', 'web', NULL, NULL),
		( 'Executive IT support', 'web', NULL, NULL),
		( 'Executive Secretary', 'web', NULL, NULL),
		( 'Facilitator', 'web', NULL, NULL),
		( 'Finance consultant', 'web', NULL, NULL),
		( 'Finance Manager', 'web', NULL, NULL),
		( 'Fire & Safety', 'web', NULL, NULL),
		( 'Fire Driver', 'web', NULL, NULL),
		( 'Fire Driver Opt', 'web', NULL, NULL),
		( 'FIRE MAN', 'web', NULL, NULL),
		( 'Fireman', 'web', NULL, NULL),
		( 'Firemen', 'web', NULL, NULL),
		( 'FMS (Electrician)', 'web', NULL, NULL),
		( 'FMS Assistant', 'web', NULL, NULL),
		( 'FMS Engineer', 'web', NULL, NULL),
		( 'Fourth Class', 'web', NULL, NULL),
		( 'front desk', 'web', NULL, NULL),
		( 'Front Desk Executive', 'web', NULL, NULL),
		( 'Front Office', 'web', NULL, NULL),
		( 'Front office Assistant', 'web', NULL, NULL),
		( 'FSA', 'web', NULL, NULL),
		( 'GD', 'web', NULL, NULL),
		( 'Generator  Operator', 'web', NULL, NULL),
		( 'Generator Operator', 'web', NULL, NULL),
		( 'GIS Exectuive', 'web', NULL, NULL),
		( 'GIS Supervisor', 'web', NULL, NULL),
		( 'GM', 'web', NULL, NULL),
		( 'Graduate Eng.', 'web', NULL, NULL),
		( 'Graduate Eng., Railwire', 'web', NULL, NULL),
		( 'Graduate Engineer', 'web', NULL, NULL),
		( 'Graphic Designer', 'web', NULL, NULL),
		( 'Hair Dresser', 'web', NULL, NULL),
		( 'Hair Stylist', 'web', NULL, NULL),
		( 'Hair Trainer', 'web', NULL, NULL),
		( 'Halper', 'web', NULL, NULL),
		( 'HD OPERATOR', 'web', NULL, NULL),
		( 'helpdesk engineer', 'web', NULL, NULL),
		( 'Helper', 'web', NULL, NULL),
		( 'Helper System Admin', 'web', NULL, NULL),
		( 'Highky Skilled', 'web', NULL, NULL),
		( 'Highly Skilled', 'web', NULL, NULL),
		( 'Hindi Consultant', 'web', NULL, NULL),
		( 'Hindi Officer', 'web', NULL, NULL),
		( 'HOUSE KEEPING', 'web', NULL, NULL),
		( 'HR Manager', 'web', NULL, NULL),
		( 'HR Recruiter', 'web', NULL, NULL),
		( 'Implementation Engineer', 'web', NULL, NULL),
		( 'Implementation Manager', 'web', NULL, NULL),
		( 'Individual Consultant', 'web', NULL, NULL),
		( 'Informat Assistant', 'web', NULL, NULL),
		( 'Informatic Assistant', 'web', NULL, NULL),
		( 'Infrastructure Expert', 'web', NULL, NULL),
		( 'Intern - HR', 'web', NULL, NULL),
		( 'IT Cell  Executive', 'web', NULL, NULL),
		( 'IT Cell Engineer', 'web', NULL, NULL),
		( 'IT Cell Executive', 'web', NULL, NULL),
		( 'IT Cell Executive/HDM', 'web', NULL, NULL),
		( 'IT Cell Incharge', 'web', NULL, NULL),
		( 'IT Cell/Implementation Engineer', 'web', NULL, NULL),
		( 'IT Engineer', 'web', NULL, NULL),
		( 'IT Manager', 'web', NULL, NULL),
		( 'IT Support', 'web', NULL, NULL),
		( 'IT Trainer', 'web', NULL, NULL),
		( 'IT-Incharge', 'web', NULL, NULL),
		( 'J.E.', 'web', NULL, NULL),
		( 'Java Developer', 'web', NULL, NULL),
		( 'JCB Driver', 'web', NULL, NULL),
		( 'JE', 'web', NULL, NULL),
		( 'Jeep Driver', 'web', NULL, NULL),
		( 'JPO', 'web', NULL, NULL),
		( 'Jr. Associate', 'web', NULL, NULL),
		( 'JR. CONSULTANT', 'web', NULL, NULL),
		( 'Jr.Consultant', 'web', NULL, NULL),
		( 'Junior Associate', 'web', NULL, NULL),
		( 'Kitchen Helper', 'web', NULL, NULL),
		( 'Lab Assistant', 'web', NULL, NULL),
		( 'LAB TECHNICIAN', 'web', NULL, NULL),
		( 'Law.O', 'web', NULL, NULL),
		( 'M & E Expert', 'web', NULL, NULL),
		( 'M P supervisor', 'web', NULL, NULL),
		( 'M&E', 'web', NULL, NULL),
		( 'Make Artist', 'web', NULL, NULL),
		( 'Makeup Trainer', 'web', NULL, NULL),
		( 'Mali', 'web', NULL, NULL),
		( 'Manager', 'web', NULL, NULL),
		( 'Manager Medical Management(claim )', 'web', NULL, NULL),
		( 'MANAGING DIRECTOR', 'web', NULL, NULL),
		( 'MANDI ANAYST', 'web', NULL, NULL),
		( 'Marketing Executive', 'web', NULL, NULL),
		( 'Mason', 'web', NULL, NULL),
		( 'Medical Consultant', 'web', NULL, NULL),
		( 'MIS - Specialist', 'web', NULL, NULL),
		( 'MIS Assistant', 'web', NULL, NULL),
		( 'MIS Asst.', 'web', NULL, NULL),
		( 'MIS SPECIALIST', 'web', NULL, NULL),
		( 'Mobile App Developer', 'web', NULL, NULL),
		( 'Mobilizer', 'web', NULL, NULL),
		( 'Monitoring & Evolution Consultant', 'web', NULL, NULL),
		( 'MSW', 'web', NULL, NULL),
		( 'MTS', 'web', NULL, NULL),
		( 'Multi Purpose Assistant', 'web', NULL, NULL),
		( 'Municipal Civil Engineer', 'web', NULL, NULL),
		( 'Network  Administrator', 'web', NULL, NULL),
		( 'Network & Secuirty Administrator', 'web', NULL, NULL),
		( 'Network Engg', 'web', NULL, NULL),
		( 'Network programmer', 'web', NULL, NULL),
		( 'Nodal Project Engineer(Civil)', 'web', NULL, NULL),
		( 'Nodal Project Engineer(Electrical)', 'web', NULL, NULL),
		( 'Nodal Project Engineer(Instrumentation)', 'web', NULL, NULL),
		( 'Nodal Project Engineer(Mechanical)', 'web', NULL, NULL),
		( 'O.T. Technician', 'web', NULL, NULL),
		( 'OE (IT)', 'web', NULL, NULL),
		( 'OFFICE ASSISSTANT', 'web', NULL, NULL),
		( 'Office Assistant', 'web', NULL, NULL),
		( 'Office Asst. Grade-2', 'web', NULL, NULL),
		( 'Office Boy', 'web', NULL, NULL),
		( 'Office Executive', 'web', NULL, NULL),
		( 'Operation Manager', 'web', NULL, NULL),
		( 'Operator', 'web', NULL, NULL),
		( 'Optometrist', 'web', NULL, NULL),
		( 'OSS', 'web', NULL, NULL),
		( 'P Care Helper', 'web', NULL, NULL),
		( 'P.T.Sweeper', 'web', NULL, NULL),
		( 'PA', 'web', NULL, NULL),
		( 'PA -Library', 'web', NULL, NULL),
		( 'Pallavi Srivastava', 'web', NULL, NULL),
		( 'Part time Chowkidar', 'web', NULL, NULL),
		( 'Part Time Maali', 'web', NULL, NULL),
		( 'Part time Sweeper', 'web', NULL, NULL),
		( 'PATIENT HELPER', 'web', NULL, NULL),
		( 'Patroller', 'web', NULL, NULL),
		( 'Pedicurist', 'web', NULL, NULL),
		( 'PEON', 'web', NULL, NULL),
		( 'Pharmacist', 'web', NULL, NULL),
		( 'PHP Developer', 'web', NULL, NULL),
		( 'Physiotherapist', 'web', NULL, NULL),
		( 'Pipe Fitter', 'web', NULL, NULL),
		( 'Plant Technician Cum Operator(Dairy Equipment)', 'web', NULL, NULL),
		( 'Plant Technician Cum Operator(Electrical)', 'web', NULL, NULL),
		( 'Plant Technician Cum Operator(Instrumentation)', 'web', NULL, NULL),
		( 'Plant Technician Cum Operator(Mechanical)', 'web', NULL, NULL),
		( 'Plant Technician Cum Operator(Refregration)', 'web', NULL, NULL),
		( 'Plumber', 'web', NULL, NULL),
		( 'PMU Executive', 'web', NULL, NULL),
		( 'PMU Incharge', 'web', NULL, NULL),
		( 'PO', 'web', NULL, NULL),
		( 'Proctor', 'web', NULL, NULL),
		( 'PROCUREMENT SPECIALIST', 'web', NULL, NULL),
		( 'Programme Associate Documentation', 'web', NULL, NULL),
		( 'Programme Associate MIS & IT', 'web', NULL, NULL),
		( 'Project Adviser', 'web', NULL, NULL),
		( 'Project Associate', 'web', NULL, NULL),
		( 'Project Co- ordinator', 'web', NULL, NULL),
		( 'Project Engineer', 'web', NULL, NULL),
		( 'Project Incharge', 'web', NULL, NULL),
		( 'Project Leader', 'web', NULL, NULL),
		( 'Project Manager', 'web', NULL, NULL),
		( 'Project Officer', 'web', NULL, NULL),
		( 'Project Support Services', 'web', NULL, NULL),
		( 'Projest Associate', 'web', NULL, NULL),
		( 'Pump Assistance', 'web', NULL, NULL),
		( 'RADIOGRAPHIC TECH.', 'web', NULL, NULL),
		( 'Radiotherapist', 'web', NULL, NULL),
		( 'Receptionist', 'web', NULL, NULL),
		( 'Record Keeper', 'web', NULL, NULL),
		( 'Register Clerk', 'web', NULL, NULL),
		( 'RETAINER-AOE CLASSIFIED', 'web', NULL, NULL),
		( 'S/G', 'web', NULL, NULL),
		( 'Safai Karamcharis', 'web', NULL, NULL),
		( 'Sale Supervisor', 'web', NULL, NULL),
		( 'Sales Promoter', 'web', NULL, NULL),
		( 'SALES SUPERVISOR', 'web', NULL, NULL),
		( 'SAO', 'web', NULL, NULL),
		( 'Scheme Assistant', 'web', NULL, NULL),
		( 'SDM /JDM', 'web', NULL, NULL),
		( 'Sec. Guard', 'web', NULL, NULL),
		( 'Secuirty Guards', 'web', NULL, NULL),
		( 'SECURITY GUARD', 'web', NULL, NULL),
		( 'Security Gurad', 'web', NULL, NULL),
		( 'Semi Skilled', 'web', NULL, NULL),
		( 'Senior Tech. Officer', 'web', NULL, NULL),
		( 'Sewermen', 'web', NULL, NULL),
		( 'SITE INCHARGE', 'web', NULL, NULL),
		( 'Skilled', 'web', NULL, NULL),
		( 'Skin Expert', 'web', NULL, NULL),
		( 'SLTC-Housing Finance Specialist', 'web', NULL, NULL),
		( 'SLTC-PPP Specialist', 'web', NULL, NULL),
		( 'SLTC-Urban Town Planner Expert', 'web', NULL, NULL),
		( 'SMM', 'web', NULL, NULL),
		( 'Social Media manager', 'web', NULL, NULL),
		( 'Software Developer', 'web', NULL, NULL),
		( 'Software Developer (.net)', 'web', NULL, NULL),
		( 'Software Developer(Mobile)', 'web', NULL, NULL),
		( 'Software Eng', 'web', NULL, NULL),
		( 'Software Engg.', 'web', NULL, NULL),
		( 'Software Engineer', 'web', NULL, NULL),
		( 'Software Manager', 'web', NULL, NULL),
		( 'Softwre Engineer', 'web', NULL, NULL),
		( 'Sr Comp Operator', 'web', NULL, NULL),
		( 'Sr Manager', 'web', NULL, NULL),
		( 'Sr Office  Asst', 'web', NULL, NULL),
		( 'Sr Sofrware Engineer', 'web', NULL, NULL),
		( 'Sr. Associate (Leather Technologist)', 'web', NULL, NULL),
		( 'Sr. Consultant', 'web', NULL, NULL),
		( 'Sr. Digital Marketing Exe', 'web', NULL, NULL),
		( 'Sr. Exec.', 'web', NULL, NULL),
		( 'SR. EXECUTIVE', 'web', NULL, NULL),
		( 'Sr. Manager', 'web', NULL, NULL),
		( 'Sr. Proctor', 'web', NULL, NULL),
		( 'Sr. Software Engineer', 'web', NULL, NULL),
		( 'Sr.Consultant', 'web', NULL, NULL),
		( 'SR.GM', 'web', NULL, NULL),
		( 'SR.SOFTWARE DEVELOPER', 'web', NULL, NULL),
		( 'SRF(Medical)', 'web', NULL, NULL),
		( 'Staff Nurse', 'web', NULL, NULL),
		( 'Stenographer', 'web', NULL, NULL),
		( 'Steward', 'web', NULL, NULL),
		( 'Store Keeper', 'web', NULL, NULL),
		( 'SUPERVISOR', 'web', NULL, NULL),
		( 'Support Engineer', 'web', NULL, NULL),
		( 'Support Enigneer', 'web', NULL, NULL),
		( 'Support Staff', 'web', NULL, NULL),
		( 'SURVEYOR-11', 'web', NULL, NULL),
		( 'Surveyor-I', 'web', NULL, NULL),
		( 'Surveyor-II', 'web', NULL, NULL),
		( 'Sweeper', 'web', NULL, NULL),
		( 'Sweeper (Part time)', 'web', NULL, NULL),
		( 'System & Adminstator', 'web', NULL, NULL),
		( 'System & DB Administrator', 'web', NULL, NULL),
		( 'System & DB Adminstatiomn', 'web', NULL, NULL),
		( 'System Admin', 'web', NULL, NULL),
		( 'System Administrator', 'web', NULL, NULL),
		( 'System Analyst', 'web', NULL, NULL),
		( 'System Engineer', 'web', NULL, NULL),
		( 'TADK/BPL', 'web', NULL, NULL),
		( 'TADK/TM/BPL', 'web', NULL, NULL),
		( 'TCPC', 'web', NULL, NULL),
		( 'Team Lead', 'web', NULL, NULL),
		( 'Team Leader', 'web', NULL, NULL),
		( 'Tech Asstt(Civil)', 'web', NULL, NULL),
		( 'Tech Asstt(Electrical)', 'web', NULL, NULL),
		( 'Tech Asstt(Mechanical)', 'web', NULL, NULL),
		( 'Techanical Developer', 'web', NULL, NULL),
		( 'Technical Assistant', 'web', NULL, NULL),
		( 'Technical Consultant', 'web', NULL, NULL),
		( 'Technical Cum Procurement Consultant', 'web', NULL, NULL),
		( 'Technical Executive', 'web', NULL, NULL),
		( 'Technical Officer', 'web', NULL, NULL),
		( 'Technical Support Staff', 'web', NULL, NULL),
		( 'Technical Writer', 'web', NULL, NULL),
		( 'Technican', 'web', NULL, NULL),
		( 'Technician', 'web', NULL, NULL),
		( 'Technician (Anaesthesia and OT)', 'web', NULL, NULL),
		( 'Technician (MLT)', 'web', NULL, NULL),
		( 'Technician (OT)', 'web', NULL, NULL),
		( 'Tele Caller', 'web', NULL, NULL),
		( 'Telecom Engineer', 'web', NULL, NULL),
		( 'Telemedicine Administrator', 'web', NULL, NULL),
		( 'Telephone Operator', 'web', NULL, NULL),
		( 'Tester', 'web', NULL, NULL),
		( 'Tractor Driver', 'web', NULL, NULL),
		( 'Trainer', 'web', NULL, NULL),
		( 'Training Officer', 'web', NULL, NULL),
		( 'Tubewell Operator', 'web', NULL, NULL),
		( 'U.T.', 'web', NULL, NULL),
		( 'Un Skilled', 'web', NULL, NULL),
		( 'Unskilled', 'web', NULL, NULL),
		( 'Unskilled labour', 'web', NULL, NULL),
		( 'Urban Infrastracture Specialist', 'web', NULL, NULL),
		( 'UT', 'web', NULL, NULL),
		( 'VCCM', 'web', NULL, NULL),
		( 'Vedio Animator', 'web', NULL, NULL),
		( 'Video Animator', 'web', NULL, NULL),
		( 'Waiter', 'web', NULL, NULL),
		( 'Watchman', 'web', NULL, NULL),
		( 'Water Man', 'web', NULL, NULL),
		( 'WC', 'web', NULL, NULL),
		( 'Web Designer', 'web', NULL, NULL),
		( 'Web Devoloper', 'web', NULL, NULL),
		( 'Weighbridge Operator', 'web', NULL, NULL),
		( 'Work Charge', 'web', NULL, NULL),
		( 'X-Ray Tech.', 'web', NULL, NULL),
		( 'Yoga Teacher', 'web', NULL, NULL),
		( 'AC Technic', 'web', NULL, NULL),
		( 'Admin Officer', 'web', NULL, NULL),
		( 'Admin. Officer', 'web', NULL, NULL),
		( 'APE', 'web', NULL, NULL),
		( 'Assistant Accountant', 'web', NULL, NULL),
		( 'Assitant Manager', 'web', NULL, NULL),
		( 'Asst.Sec.Off.', 'web', NULL, NULL),
		( 'Attandant', 'web', NULL, NULL),
		( 'Attendant', 'web', NULL, NULL),
		( 'Backend Support- Sales Account', 'web', NULL, NULL),
		( 'BDE', 'web', NULL, NULL),
		( 'BDE.', 'web', NULL, NULL),
		( 'Care Taker', 'web', NULL, NULL),
		( 'Carpenter', 'web', NULL, NULL),
		( 'Ceretaker', 'web', NULL, NULL),
		( 'CFO', 'web', NULL, NULL),
		( 'Computer Assistant', 'web', NULL, NULL),
		( 'CONDUCTOR', 'web', NULL, NULL),
		( 'CRM Support', 'web', NULL, NULL),
		( 'Drivers', 'web', NULL, NULL),
		( 'Executive Officer', 'web', NULL, NULL),
		( 'Ground Man', 'web', NULL, NULL),
		( 'Gym Instructor', 'web', NULL, NULL),
		( 'Gym Instructor Female', 'web', NULL, NULL),
		( 'Housekeeping', 'web', NULL, NULL),
		( 'HRMS Operator', 'web', NULL, NULL),
		( 'Incharge, Sanathnagar Branch', 'web', NULL, NULL),
		( 'Jr.Attandant', 'web', NULL, NULL),
		( 'KPO', 'web', NULL, NULL),
		( 'Lab Asstt.', 'web', NULL, NULL),
		( 'Lab Attandant', 'web', NULL, NULL),
		( 'Line Attendant', 'web', NULL, NULL),
		( 'Manager Admin & Accounts', 'web', NULL, NULL),
		( 'Masson', 'web', NULL, NULL),
		( 'MECHANIC', 'web', NULL, NULL),
		( 'Meter Reader', 'web', NULL, NULL),
		( 'MIS executive', 'web', NULL, NULL),
		( 'MR', 'web', NULL, NULL),
		( 'Multipurpose Health Worker', 'web', NULL, NULL),
		( 'Na', 'web', NULL, NULL),
		( 'Office Attendant/Helper', 'web', NULL, NULL),
		( 'Pharnamcist', 'web', NULL, NULL),
		( 'Project Assistant', 'web', NULL, NULL),
		( 'Pump Operator', 'web', NULL, NULL),
		( 'Retainer', 'web', NULL, NULL),
		( 'Security', 'web', NULL, NULL),
		( 'Security guard Cum Housekeeping', 'web', NULL, NULL),
		( 'Security Supervisor', 'web', NULL, NULL),
		( 'Sewarman', 'web', NULL, NULL),
		( 'Sewarmen', 'web', NULL, NULL),
		( 'Sports Ground Supervisor', 'web', NULL, NULL),
		( 'Sr. Officer', 'web', NULL, NULL),
		( 'SSMIDS', 'web', NULL, NULL),
		( 'State Accountant', 'web', NULL, NULL),
		( 'State Financial Inclusion & Micro Ent Specialist', 'web', NULL, NULL),
		( 'State HR & Capacity Building Specialist', 'web', NULL, NULL),
		( 'State MIS & ME Specialist', 'web', NULL, NULL),
		( 'State Project Engineering Specialist', 'web', NULL, NULL),
		( 'State Skills & Livelihoods Specialist', 'web', NULL, NULL),
		( 'Substation Operator', 'web', NULL, NULL),
		( 'Sweeper&Servant', 'web', NULL, NULL),
		( 'TCB', 'web', NULL, NULL),
		( 'Tech Assistant', 'web', NULL, NULL),
		( 'Town Community Organizers', 'web', NULL, NULL),
		( 'Town Financial Inclusion & Micro Ent. Specialist', 'web', NULL, NULL),
		( 'Town MIS & ME Specialist', 'web', NULL, NULL),
		( 'Town Project Engineering Specialist', 'web', NULL, NULL),
		( 'Town Skills Livelihoods/Micro Ent. Specialist', 'web', NULL, NULL),
		( 'Town Social Mob. & Instituional Specialist', 'web', NULL, NULL),
		( 'Training & placement asstt.', 'web', NULL, NULL),
		( 'Welder', 'web', NULL, NULL),
		( 'Worker', 'web', NULL, NULL),
		( 'CB SPECIALIST STATE', 'web', NULL, NULL),
		( 'CIVIL ENGINEER (STATE)', 'web', NULL, NULL),
		( 'Expert', 'web', NULL, NULL),
		( 'Horticulture Supervisor', 'web', NULL, NULL),
		( 'HOUSING FINANCE AND POILCY SPECIALIST', 'web', NULL, NULL),
		( 'KNOWLEDGE MANAGEMENT (STATE)', 'web', NULL, NULL),
		( 'MESSENGER', 'web', NULL, NULL),
		( 'MIS & ME Expert', 'web', NULL, NULL),
		( 'MIS SPECIALIST STATE', 'web', NULL, NULL),
		( 'PFMS Expert', 'web', NULL, NULL),
		( 'PPP SPECIALIST (STATE)', 'web', NULL, NULL),
		( 'SD SPECIALIST STATE', 'web', NULL, NULL),
		( 'SMID', 'web', NULL, NULL),
		( 'State Capacity building Specialist', 'web', NULL, NULL),
		( 'State MIS Specialist', 'web', NULL, NULL),
		( 'State Municipal Finance Specialist', 'web', NULL, NULL),
		( 'State Procurement Specialist', 'web', NULL, NULL),
		( 'State Project Engineer', 'web', NULL, NULL),
		( 'State Shelter and Social Infrastructure Specialist', 'web', NULL, NULL),
		( 'State Skills & Livelihood Specialist', 'web', NULL, NULL),
		( 'State Social Mobilization Expert', 'web', NULL, NULL),
		( 'State Urban Infrastructure', 'web', NULL, NULL),
		( 'State Urban Planner', 'web', NULL, NULL),
		( 'TCO', 'web', NULL, NULL),
		( 'Town Civil Engineer', 'web', NULL, NULL),
		( 'Town Urban Planner', 'web', NULL, NULL),
		( 'URBAN PLANNER', 'web', NULL, NULL),
		( 'URBAN PLANNER (STATE)', 'web', NULL, NULL),
		( 'Accounts Executive', 'web', NULL, NULL),
		( 'AM', 'web', NULL, NULL),
		( 'AO', 'web', NULL, NULL),
		( 'Auditor', 'web', NULL, NULL),
		( 'AVP', 'web', NULL, NULL),
		( 'Branch Service Co-Ordinator', 'web', NULL, NULL),
		( 'Business Associate Sales', 'web', NULL, NULL),
		( 'Business Associate-Sales', 'web', NULL, NULL),
		( 'CLERK', 'web', NULL, NULL),
		( 'Co-Ordinator', 'web', NULL, NULL),
		( 'Director', 'web', NULL, NULL),
		( 'Engineer Service', 'web', NULL, NULL),
		( 'Helper Store asst.', 'web', NULL, NULL),
		( 'INSPECTOR', 'web', NULL, NULL),
		( 'Law officer', 'web', NULL, NULL),
		( 'Multi Task', 'web', NULL, NULL),
		( 'Office Asst.', 'web', NULL, NULL),
		( 'Pantry Boy', 'web', NULL, NULL),
		( 'Sales co-ordinator', 'web', NULL, NULL),
		( 'Sarbjit Singh', 'web', NULL, NULL),
		( 'Service Ambasdor', 'web', NULL, NULL),
		( 'Service Executive', 'web', NULL, NULL),
		( 'Service Technician', 'web', NULL, NULL),
		( 'Store Asst.', 'web', NULL, NULL),
		( 'Store Helper', 'web', NULL, NULL),
		( 'Superwiser', 'web', NULL, NULL),
		( 'TIME KEEPER', 'web', NULL, NULL),
		( 'Trainee', 'web', NULL, NULL),
		( 'Washerman', 'web', NULL, NULL),
		( 'Jr. Quality Auditor', 'web', '2019-03-05 06:03:45', '2019-03-05 06:05:54'),
		( 'Designer', 'web', '2019-04-05 23:12:05', '2019-04-05 23:13:55'),
		( 'Software Tester', 'web', '2019-05-01 06:56:33', '2019-05-01 06:56:33'),
		( 'System Admin - IT', 'web', '2019-05-02 13:20:37', '2019-05-02 13:20:37'),
		( 'Asst. Manager - IT', 'web', '2019-05-02 13:20:53', '2019-05-02 13:20:53'),
		( 'Digital Marketing', 'web', '2019-05-02 14:06:39', '2019-05-02 14:06:39'),
		( 'Vice President', 'web', '2019-05-02 16:33:58', '2019-05-11 13:24:34'),
		( 'Recruiter', 'web', '2019-05-03 11:28:28', '2019-05-03 11:28:28'),
		( 'HR-Executive', 'web', '2019-05-03 17:00:07', '2019-05-03 17:00:07'),
		( 'Trainee-HR', 'web', '2019-05-03 17:01:18', '2019-05-03 17:01:18'),
		( 'Sr. Quality Auditor', 'web', '2019-05-03 17:18:12', '2019-05-03 17:18:12');");
    }
}
